# Generated by Django 5.2.1 on 2025-10-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visualization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weathermetric",
            name="cloud_cover",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weathermetric",
            name="rainfall",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weathermetric",
            name="uv_index",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weathermetric",
            name="visibility",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weathermetric",
            name="wind_direction",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weathermetric",
            name="wind_speed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
